### ISSUE TITLE
Publish to NPM

### ISSUE THREAD

**Issue by gavboulton** [mailcheck/mailcheck#94] opened 2015-02-13 16:57 UTC
I'd really like to use this updated version as an NPM module. Please can you publish it?

**Comment by weilu** [comment] 2015-02-16 12:07
@aseemk Can you update the npm module to 1.1.0 please?

@derrickko Would you like @aseemk to transfer the ownership to you? I can take it if you aren't comfortable with npm.

**Comment by gavboulton** [comment] 2015-02-16 12:21
Does the version number need to be bumped up due to the recent second level domain addition?

**Comment by weilu** [comment] 2015-02-16 13:31
When #95 is confirmed and merged, yes

**Comment by aseemk** [comment] 2015-02-16 15:08
Hi folks,

I already added @derrickko to the owners list a while back:

```
$ npm owner ls mailcheck
aseemk <aseem.kishore@gmail.com>
dko <hello@derrickko.com>
```

He is free to publish this update, remove me from the owners list, anything. =)

@weilu: I'm also happy to add you as an owner; just let me know your npm username.

**Comment by weilu** [comment] 2015-02-18 01:14
Yes, please. It's weilu. Thank you @aseemk.

**Comment by aseemk** [comment] 2015-02-18 02:22
Done!

**Comment by weilu** [comment] 2015-02-18 12:14
Thank you @aseem! :)

Cheers
Wei

**Comment by joshfrench** [comment] 2015-03-16 18:53
Can somebody push v1.1.0 to NPM? Thanks!

**Comment by weilu** [comment] 2015-03-18 13:34
Done!

**Closed by weilu** 2015-03-18 13:34 UTC

**Comment by gavboulton** [comment] 2015-03-18 13:57
v1.1.0 was released in August 2014. 

Now that https://github.com/mailcheck/mailcheck/pull/95 has been merged, can you bump the version number and release NPM please.

This is what I wanted in my initial comment.

Thanks!

**Comment by weilu** [comment] 2015-03-18 16:00
v1.1.0 wasn't released in NPM back then. I'm hesitant about tagging a new version because I think the current default values are broken (see #96, #97). All that said, I don't use this library in any of my current projects, so I'd like to hear from those ones who are actually using it. Ping @derrickko @kevinhughes27

**Comment by kevinhughes27** [comment] 2015-03-18 17:25
I'm using a complete set of custom domains and tighter thresholds in production. I asked about making those defaults but no one has answered or taken action

**Comment by derrickko** [comment] 2015-03-18 17:31
@kevinhughes27 I saw your comment in https://github.com/mailcheck/mailcheck/pull/89. Do the PR with your defaults and I'll merge it in.

**Comment by kevinhughes27** [comment] 2015-03-18 17:42
okay I'll try and get a PR together soon (~couple of days)
